name: Python Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install testing dependencies
      run: pip install -r test/requirements.txt
    - name: Set up certificate
      run: |
        openssl genrsa -out key.pem 2048
        openssl req -new -x509 -key key.pem -out cert.pem -days 365 -subj "/C=US/ST=State/L=City/O=Organization/OU=OrganizationalUnit/CN=www.example.com"
    - name: Run unit tests
      run: python -u test/unit_test.py
